# vim: set ts=2 sw=2 sts=2 et :

version: '2.2'

services:
  testthisplease:
    image: jenkinstestthisplease:${TTP_TAG:-latest}
    environment:
      - JENKINS_USERNAME=foo
      - JENKINS_PASSWORD=bar
      - JENKINS_URL=https://jenkins.foo.com
      - JENKINS_ORG=jenkinsci
      - JENKINS_PROJECT=jenkins
      - JENKINS_BUILD_PARAMS='FORCE_BUILD=true'
      - GITHUB_S2S_SECRET=myAwesomeSuperStrongSecret
    ports:
      - "8000:80"
